### ISSUE TITLE
Missing textures Allthemodium to Silent Gears

### ISSUE THREAD

**Issue by Thunder-Nova** [AllTheMods/ATM-5#206]
## Expected Behavior

Having this yellowish armor and sword

## Current Behavior

I look like deadpool who forgot to add eye holes to his suit with a blade-less sword.
![image](https://user-images.githubusercontent.com/31967337/88236346-c13f0380-cc4a-11ea-9317-b9624c246f1b.png)
![image](https://user-images.githubusercontent.com/31967337/88236368-d451d380-cc4a-11ea-8be2-93c367cc0ff6.png)

## Possible Solution

Retexturize?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by thevortex** [comment]
issue corrected with next update of Allthemodium(v0.9.2.1)

**Comment by GatekeeperTDS** [comment]
Hi vortex - I'm on ATM5 2.14 now, which has allthemodium-0.9.17-1.15.2-31.2.0.jar. I think these textures are still broken.

![image](https://user-images.githubusercontent.com/66881994/89093215-3f578480-d386-11ea-9109-d6655a06dc0c.png)

**Comment by Thunder-Nova** [comment]
@GatekeeperTDS It's not just textures, it's the actual material that is missing...

**Comment by Thunder-Nova** [comment]
@thevortex could it be that it doesn't recognize the material? Perhaps adding something as:

- Allthemodium:Allthemodium
- Allthemodium:Vibranium

... idk if it's silent gear side as well.

**Comment by thevortex** [comment]
fix coming tomorrow
