### ISSUE TITLE
Conflicting recipes for Mystical Aggriculture essences

### ISSUE THREAD

**Issue by jinkhya** [AllTheMods/ATM-5#45]
Hello,
Since ATM5 updated to 1.12 some of the recipes for the essences conflict with each other.
Like those : https://i.imgur.com/7GFE1q1.png

This is due to the Cucumber update. Reverting to Cucumber-1.15.2-3.0.1.jar fixed the issue (but ironjetpacks needs 3.0.2)

Best regards,
Jin

**Comment by Quu1337** [comment]
Noticed them too after the update, reported it yesterday and now pinned this issue to dev-channel too.

**Comment by jeremiahwinsley** [comment]
Wood essence also has multiple overlaps

**Comment by oly2o6** [comment]
nature essence is fixed i will work on wood essence and all should be in friday

**Comment by redaktiv** [comment]
The update didn't fix this completely. Jungle log and saplings still share recipes with Dark Oak log and saplings

**Comment by redaktiv** [comment]
1.17 update didn't fix this. Jungle saplings still share recipes with Dark Oak saplings
